version: '3.7'

services:

  esdb:
    image: eventstore/eventstore:latest #20.10.2-buster-slim
    ports:
      - '2113:2113'
      - '1113:1113'
    environment:
      EVENTSTORE_INSECURE: 'true'
      EVENTSTORE_CLUSTER_SIZE: 1
      EVENTSTORE_EXT_TCP_PORT: 1113
      EVENTSTORE_HTTP_PORT: 2113
      EVENTSTORE_ENABLE_EXTERNAL_TCP: 'true'
      EVENTSTORE_RUN_PROJECTIONS: all
      EVENTSTORE_START_STANDARD_PROJECTIONS: "true"
      EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: "true"
    networks:
      - starlight-one
      
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - starlight-one

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - starlight-one

  prometheus:
    image: prom/prometheus:v2.17.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - starlight-one

  grafana:
   image: grafana/grafana:6.7.2
   ports:
     - "3000:3000"
   volumes:
     - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yaml
     - ./grafana/dashboards:/dashboards

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"

  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - starlight-one

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - starlight-one
      
networks:
  starlight-one:
