name: Starlight-one

extensions:
  - name: dapr
    enable-profiling: true
    services: 
      swagger:
        enabled: false
      health:
        enabled: false

  - name: zipkin
  - name: seq
    logPath: ./.logs

ingress:
  - name:  ingress
    bindings:
      - port: 8001
    rules:
      - path: /swagger
        service: swagger
      - path: /health
        service: health
      - path: /starships/command
        service: starships-command-api

services:
  - name: swagger
    project: src/Framework/src/StarlightOne.Swagger/StarlightOne.Swagger.csproj
    bindings:
      - protocol: http
      
  - name: health
    project: src/Framework/src/StarlightOne.Health/StarlightOne.Health.csproj
    bindings:
      - protocol: http
    
  - name: starships-command-api
    project: src/Starships/src/Starships.CommandApi/Starships.CommandApi.csproj
    bindings:
      - protocol: http
    env:
    - name: Ingress:PathBase
      value: /starships/command
            
  #
  #
  #- name: dapr-placement
  #  image: daprio/dapr
  #  bindings:
  #    - port: 50006
    
  - name: redis
    image: redis
    bindings:
      - port: 6379      
    
    #- name: redis-cli
    #  image: redis
    #  args: "redis-cli -h redis MONITOR"

  - name: mongodb
    image: mongo
    bindings:
      - port: 27017
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: mongoadmin
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: secret

#      
#- name: esdb
#  image: eventstore/eventstore:latest
#  bindings:
#    - port: 2113
#      containerPort: 2113
#      protocol: http
#    - port: 1113
#      containerPort: 1113
#      protocol: http
#    env:
#      - name: EVENTSTORE_INSECURE
#        value: true
#      - name: EVENTSTORE_CLUSTER_SIZE
#        value: 1
#      - name: EVENTSTORE_EXT_TCP_PORT
#        value: 1113
#      - name: EVENTSTORE_HTTP_PORT
#        value: 2113
#      - name: EVENTSTORE_ENABLE_EXTERNAL_TCP
#        value: true
#      - name: EVENTSTORE_RUN_PROJECTIONS
#        value: all
#      - name: EVENTSTORE_START_STANDARD_PROJECTIONS
#        value: true
#      - name: EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP
#        value: true  