name: Starlight-one

extensions:
  - name: dapr
    enable-profiling: true
    placement-port: 50006
    services:
      openapi:
        enabled: false
      health:
        enabled: false
        
  - name: zipkin
  - name: seq
    logPath: ./.logs

ingress:
  - name:  ingress
    bindings:
      - port: 8001
    rules:
      - path: /openapi
        service: openapi
      - path: /health
        service: health
      - path: /api/starships/command
        service: starships-command-api      
      - path: /api/starships/query
        service: starships-query-api

services:
  - name: openapi
    project: src/Framework/src/StarlightOne.OpenApi/StarlightOne.OpenApi.csproj
    bindings:
      - protocol: http
    env: 
    - name: Ingress:PathBase
      value: /openapi
    - name: Swagger:Docs:0:Name
      value: starships-command
    - name: Swagger:Docs:0:Url
      value: /api/starships/command/swagger/v1/swagger.json    
    - name: Swagger:Docs:1:Name
      value: starships-query
    - name: Swagger:Docs:1:Url
      value: /api/starships/query/swagger/v1/swagger.json
        
  - name: health
    project: src/Framework/src/StarlightOne.Health/StarlightOne.Health.csproj
    bindings:
      - protocol: http
    
  - name: starships-command-api
    project: src/Starships/src/Starships.CommandApi/Starships.CommandApi.csproj
    bindings:
      - protocol: http
    env:
    - name: Ingress:PathBase
      value: /api/starships/command

  - name: starships-command-service
    project: src/Starships/src/Starships.CommandService/Starships.CommandService.csproj
    bindings:
      - protocol: http

  - name: starships-query-api
    project: src/Starships/src/Starships.QueryApi/Starships.QueryApi.csproj
    bindings:
      - protocol: http
    env:
      - name: Ingress:PathBase
        value: /api/starships/query
        
  - name: starships-query-service
    project: src/Starships/src/Starships.QueryService/Starships.QueryService.csproj
    bindings:
      - protocol: http        
        
  # run own dapr-placement service to keep all in one   
  - name: dapr-placement
    image : daprio/dapr:1.6.0
    args: ./placement -port 50006
    bindings:
      - port: 50006

  - name: redis
    image: redis
    bindings:
      - port: 6379      
    
    #- name: redis-cli
    #  image: redis
    #  args: "redis-cli -h redis MONITOR"

  - name: mongodb
    image: mongo
    bindings:
      - port: 27017
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: mongoadmin
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: secret

#      
#- name: esdb
#  image: eventstore/eventstore:latest
#  bindings:
#    - port: 2113
#      containerPort: 2113
#      protocol: http
#    - port: 1113
#      containerPort: 1113
#      protocol: http
#    env:
#      - name: EVENTSTORE_INSECURE
#        value: true
#      - name: EVENTSTORE_CLUSTER_SIZE
#        value: 1
#      - name: EVENTSTORE_EXT_TCP_PORT
#        value: 1113
#      - name: EVENTSTORE_HTTP_PORT
#        value: 2113
#      - name: EVENTSTORE_ENABLE_EXTERNAL_TCP
#        value: true
#      - name: EVENTSTORE_RUN_PROJECTIONS
#        value: all
#      - name: EVENTSTORE_START_STANDARD_PROJECTIONS
#        value: true
#      - name: EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP
#        value: true  