GET http://localhost:8001/api/starships/query/starship/list
Accept: application/json

###
GET http://localhost:3500/v1.0/invoke/starships-query-service/method/starship/list
Accept: application/json

###
GET http://localhost:3500/v1.0/invoke/starships-query-service/method/starship/list2
Accept: application/json

###

GET http://localhost:5020/starship/list
Accept: application/json
